
on:
  push:
    branches: 
      - main
  workflow_dispatch:


jobs:
  windows-test-job:
    runs-on: windows-latest

    steps:
      - name: Enable CL
        uses: ilammy/msvc-dev-cmd@v1.13.0
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: ml64
        shell: bash
        run: which ml64

      - name: cl
        run: where cl

      - run: echo "Hello"

  linux-test-job:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello"
      