
on:
  push:
    branches: 
      - main
  workflow_dispatch:


jobs:
  windows-test-job:
    runs-on: windows-latest

    steps:
      - run: echo "Hello"

      - name: hostfxr.dll
        shell: cmd
        run: dir "C:\Program Files\dotnet\host\fxr" # dir "C:\Program Files\dotnet\host\fxr\10.0.3"
            

          
  linux-test-job:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello"
      
      - name: Test
        run: |
          FXR_PATH=$(printf ":%s" /usr/share/dotnet/host/fxr/8.*)
          FXR_PATH=${FXR_PATH:1}

          echo ${FXR_PATH}

      #- name: hostfxr
      #  run: sudo find / -name libhostfxr.so

  
  linux-arm-test-job:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Setup Project
        run: |
          printf "#include <iostream>\nint main(int argc, char** argv)\n{\nstd::cout << 123 << std::endl;\nreturn 0;\n}\n" > file.cpp
          printf "cmake_minimum_required(VERSION 3.27.0)\nproject(Program)\nadd_library(${PROJECT_NAME} file.cpp)\nmessage(${CMAKE_HOST_SYSTEM_PROCESSOR})\nmessage(${CMAKE_SYSTEM_PROCESSOR}))" > CMakeLists.txt
          cat CMakeLists.txt

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . -j
